dist: trusty
sudo: false
rvm:
  - 2.5.3
# Travis currently translates "2.5" into "2.5.4", which has bundler problems.
# This build is here to discover when "2.5" stops breaking. It's allowed to fail by
# the "matrix" key, below
  - 2.5
matrix:
  allow_failures:
    - rvm: 2.5
env:
  global:
    - TF_VERSION="0.11.14"
    - BOSH_CLI_VERSION="2.0.48"
    - PROMETHEUS_VERSION="2.6.1"
    - DEPLOY_ENV="travis"
    - TMPDIR="/tmp"

addons:
  apt:
    sources:
      - git-core
    packages:
      - git
      - gnupg

before_install:
  - |
    mkdir ~/bin
    export PATH=~/bin:$PATH
  - |
    echo "Fetching shellcheck"
    set -e
    wget -O ~/bin/shellcheck https://github.com/alphagov/paas-cf/releases/download/shellcheck_binary_0.4.6/shellcheck_linux_amd64
    chmod +x ~/bin/shellcheck
    set +e
  - |
    echo "Fetching Terraform"
    set -e
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d ~/bin
    rm terraform_${TF_VERSION}_linux_amd64.zip
    set +e
  - |
    echo "Fetching bosh cli v2"
    set -e
    wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-${BOSH_CLI_VERSION}-linux-amd64
    mv bosh-cli-${BOSH_CLI_VERSION}-linux-amd64 ~/bin/bosh && chmod +x ~/bin/bosh
    set +e
  - |
    echo "Fetching Promtool ${PROMETHEUS_VERSION}"
    set -e
    wget -O prometheus.tgz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz"
    tar xzf "prometheus.tgz" \
       -C $HOME/bin/ \
       --wildcards \
       --wildcards-match-slash \
       --strip-components=1 \
       '*promtool'
    set +e
  - pip install --user yamllint
  - GIMME_OUTPUT=$(gimme 1.12 | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/alphagov/paas-cf
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/alphagov/paas-cf/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/alphagov/paas-cf
  - cd $HOME/gopath/src/github.com/alphagov/paas-cf

script:
  - make test
