# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'fog'

Vagrant.require_version ">= 1.8.0"

aws_region = 'us-east-1'

fog_config = {
  :provider              => :aws,
  :region                => aws_region
}
fog_config[:aws_access_key_id] = ENV['AWS_ACCESS_KEY_ID']
fog_config[:aws_secret_access_key] = ENV['AWS_SECRET_ACCESS_KEY']
aws_client = Fog::Compute.new(fog_config)

# We sort by version as fog doesn't expose the creation date
concourse_amis = aws_client.images.all({'name' => 'concourse-v*'})
raise "No concourse ami found in region #{aws_region}" if concourse_amis.length == 0
sorted_amis = concourse_amis.sort! { |a,b| a.name <=> b.name }

ami_id = sorted_amis[0].id
subnet_id = aws_client.subnets.all[0].subnet_id
security_group = aws_client.security_groups.get('Bootstrap Concourse').group_id

Vagrant.configure(2) do |config|
  config.vm.box = ENV['VAGRANT_BOX_NAME'] || 'aws_vagrant_box'

  Dir.glob("./post-deploy.d/*").sort.each do |post_deploy_file|
    config.vm.provision "shell" do |s|
      s.privileged = true
      s.env = ENV.select {
        |key| ['CONCOURSE_ATC_PASSWORD', 'CONCOURSE_ATC_USER'].include? key
      }
      s.name = post_deploy_file
      s.path = post_deploy_file
    end
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.associate_public_ip = true
    aws.tags = { 'Name' => (ENV['DEPLOY_ENV'] || ENV['USER']) + " concourse" }

    aws.ami = ami_id
    aws.region = aws_region

    # Only HVM instances with ephemeral disks can be used
    aws.instance_type = 'm3.large'

    aws.subnet_id = subnet_id
    aws.security_groups = [security_group]

    # Add IAM role to allow access to necessary AWS APIs
    aws.iam_instance_profile_name = 'bootstrap-concourse'

    # We will rely on vagrant generating a ssh key, but this must be the ubuntu user, as the vagrant user does not exist on the vm
    override.ssh.username = "ubuntu"

    # Fix issue on osx: https://github.com/mitchellh/vagrant/issues/5401#issuecomment-115240904
    override.nfs.functional = false
  end

end
